### ISSUE TITLE
Add Swapzone.io to the listing

### ISSUE THREAD

**Issue by Kronkmeister** [ecashxec/scorecard-cash-info#8]
https://swapzone.io/ seems to be missing in the scorecardlisting, while it supports XEC swaps. 

Please add it to the listing. thank you

**Comment by johnkuney** [comment]
@Kronkmeister thank you for opening the issue. We will get it added as soon as possible

**Comment by johnkuney** [comment]
@Kronkmeister apologies for the the delay, but we aren't listing aggregators at this time so will be closing this issue
