### ISSUE TITLE
Add The Week in eCash from eCashNEWS.today

### ISSUE THREAD

**Issue by EverydayPerson** [ecashxec/scorecard-cash-info#9]
Add The Week in eCash from eCashNEWS.today

https://www.ecashnews.today/
<img width="934" alt="Screen Shot 2021-11-18 at 10 45 28 AM" src="https://user-images.githubusercontent.com/6447316/142477590-25f2d654-30c2-42ea-b78a-61d74efbb19a.png">

**Comment by johnkuney** [comment]
Cool site, but scorecard is more geared towards listing projects that deal with displaying prices, addresses, numbers etc. News sites like this are good but not relevant to this particular site
